# https://github.com/PalmStoneGames/kube-cert-manager/blob/master/buildspec.yml
version: 0.1

environment_variables:
  plaintext:
    SRC_DIR: /go/src/github.com/mweagle/SpartaCodePipeline
    PIPELINE_PACKAGE: SpartaCodePipeline.zip

phases:
  pre_build:
    commands:
      - env
      - go get -u github.com/golang/dep/cmd/dep
      - mkdir -pv $SRC_DIR && mv $PWD/* $SRC_DIR/ && cd $SRC_DIR && dep ensure -v
  build:
    commands:
      - cd $SRC_DIR && go run main.go provision --level info --s3Bucket weagle --codePipeline $PIPELINE_PACKAGE
  post_build:
    commands:
      - ls -laR $SRC_DIR

artifacts:
  files:
    - $SRC_DIR/.sparta/$PIPELINE_PACKAGE