# https://github.com/PalmStoneGames/kube-cert-manager/blob/master/buildspec.yml
version: 0.1

environment_variables:
  plaintext:
    SRC_DIR: /go/src/github.com/mweagle/SpartaCodePipeline

phases:
  pre_build:
    commands:
      - env
      - mkdir -pv $SRC_DIR && mv $PWD/* $SRC_DIR/ && cd $SRC_DIR && go get -v ./...
  build:
    commands:
      - cd $SRC_DIR && go run main.go provision --level info --s3Bucket weagle --codePipeline SpartaCodePipeline.zip

  artifacts:
    ./.sparta/SpartaCodePipeline.zip